hmrc/childcare-calculator-frontend

app/uk/gov/hmrc/childcarecalculatorfrontend/config/frontendGlobal.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/HelloWorld.scala
conf/application.conf
conf/logback.xml
conf/prod.routes
project/MicroService.scala

@milena-valchanova , @zatevad , @kapil-sanghvi

Ccalc 3040

---

conf/app.routes
project/MicroService.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/FakeCCApplication.scala

Ccalc 3060

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/ccMain.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/govuk_wrapper.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/main_template.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatYouNeed.scala.html
conf/app.routes
conf/messages
public/stylesheets/cc.css
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhatYouNeedSpec.scala

@shridhaarchippaa @kapil-sanghvi @zatevad

Ccalc 3043

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildCareBaseController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/govuk_wrapper.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/main_template.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/technicalDifficulties.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ChildCareBaseControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/TechnicalDifficultiesSpec.scala

Ccalc 3084

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/ChildAgedThreeOrFourForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/ChildAgedTwoForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/LocationForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CCConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/childAgedTwo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/error/ccErrorSummary.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/location.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/ChildAgedThreeOrFourFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/ChildAgedTwoFormSpec.scala

@shridhaarchippaa @kapil-sanghvi @zatevad

Ccalc 3006

---

app/uk/gov/hmrc/childcarecalculatorfrontend/config/frontendAppConfig.scala
conf/application.conf

@kapil-sanghvi @milena-valchanova @zatevad

Updated eligibility service url

---

conf/application.conf

Updated the version of assets frontend that we use, as there has been a PR to include the styling of the new radio buttons etc. Good news!

new assets frontend version so we can use the new radio buttons etc

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursInfoController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursResultsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/ccMain.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/govuk_wrapper.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursResults.scala.html
conf/messages
public/stylesheets/cc.css
test/uk/gov/hmrc/childcarecalculatorfrontend/TemplatesValidator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursInfoControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursResultsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/FreeHoursInfoSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/FreeHoursResultsSpec.scala

@milena-valchanova @shridhaarchippaa @zatevad I have added the styles to the results page. Please review and merge.

Ccalc 3100

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/HoursController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PaidEmploymentController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichOfYouInPaidEmploymentController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursResults.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PaidEmploymentControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichOfYouInPaidEmploymentControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/FreeHoursInfoSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/FreeHoursResultsSpec.scala

commented no cost content

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursResultsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Household.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursResultsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/services/KeystoreServiceSpec.scala

Add test connection for calculations

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ExpectChildcareCostsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/FreeHoursResultsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/HoursController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/LivingWithPartnerController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PaidEmploymentController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/VouchersController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichOfYouInPaidEmploymentController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/VouchersForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Enums.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Household.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CCConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/vouchers.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/CCRoutes.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ExpectChildcareCostsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/HoursControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/LivingWithPartnerControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PaidEmploymentControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/VouchersControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/VouchersFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ChildAgedTwoSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/VouchersSpec.scala

Ccalc 3133

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/GetBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/LocationController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichBenefitsDoYouGetController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoGetsBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhichBenefitsDoYouGetForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Enums.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Household.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CCConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/FormManager.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/checkbox/ccCheckboxOptions.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/error/checkboxInLineErrorMessage.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/CCRoutes.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/TemplatesValidator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/GetBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichBenefitsDoYouGetControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoGetsBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhichBenefitsDoYouGetFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BenefitsSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhoGetsBenefitsSpec.scala

Ccalc 3143

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/common/ccInput.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/hours.scala.html
public/stylesheets/cc.css

@shridhaarchippaa please merge

input styles updated

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhatsYourAgeController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/HoursForm.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/HoursFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/HoursSpec.scala

Ccalc 3290

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/GetBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/VouchersController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichOfYouInPaidEmploymentController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoGetsVouchersController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoGetsVouchersForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Household.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CCConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whoGetsVouchers.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/CCRoutes.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/GetBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/VouchersControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichOfYouInPaidEmploymentControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhoGetsVouchersControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoGetsVouchersFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhoGetsVouchersSpec.scala

@shridhaarchippaa @zatevad please review

Ccalc 3301

---

README.md
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/MinimumEarningsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhatsYourAgeController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichBenefitsDoYouGetController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhichOfYouInPaidEmploymentController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/MinimumEarningsForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Household.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/CCConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/HelperManager.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/minimumEarning.scala.html
conf/app.routes
conf/application.conf
conf/messages
conf/nmw.conf
test/uk/gov/hmrc/childcarecalculatorfrontend/CCRoutes.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/FakeCCApplication.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/TemplatesValidator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/MinimumEarningsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhatsYourAgeControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/MinimumEarningFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/utils/HelperManagerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/MinimumEarningSpec.scala

Ccalc 3153

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_check_box.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_radio.scala.html
conf/application.conf
project/plugins.sbt

@Muhammad-Ali-Ahmad @chandankumarray

Renamed appName

---

project/MicroService.scala
project/plugins.sbt

Updated plugins and Microservice

---

project/FrontendBuild.scala
project/MicroService.scala

removed appVersion

---

conf/application.conf

Upgrade assets frontend

---

app/assets/javascripts/polyfill.js
project/MicroService.scala

@shridhaarchippaa can you please merge

polyfill added for accessibility

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/detail_summary.scala.html

@shridhaarchippaa please merge

CCALC-3702 details updated

---

app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/PensionNavigator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/PensionNavigatorSpec.scala

Reverts hmrc/childcare-calculator-frontend#89

Revert "CCALC-3691,3692,3694 Navigation from pension to benefits"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/PensionNavigator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/PensionNavigatorSpec.scala

Reverts hmrc/childcare-calculator-frontend#88

Revert "fixed navigation for Are you/Partner/Both paying into a work pension …"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/BenefitsNavigator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/BenefitsNavigatorSpec.scala

Reverts hmrc/childcare-calculator-frontend#90

Revert "navigation completed from  Have you had any of these benefits this ye…"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/areYouInPaidWork.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/maxFreeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatIsYourTaxCode.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourMaximumEarnings.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/AreYouInPaidWorkViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/MaxFreeHoursInfoViewSpec.scala

Added missing content to page, and new content to test

paid work content update

---

app/assets/stylesheets/childcarecalculatorfrontend-app.scss
app/assets/stylesheets/partials/_typography.scss
conf/messages.en

Override of p and h1 tag spacing and content change to what you need

Content check

---

app/uk/gov/hmrc/childcarecalculatorfrontend/models/Household.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHousehold.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/services/EligibilityService.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/DisabilitySpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHouseholdSpec.scala

Updated to store correct values when child is registered blind. We're going to test the returned values when we've fixed the TAX code issue (this is in another story)

CCALC-3784: Registered Blind is not stored in the Household object

---

app/uk/gov/hmrc/childcarecalculatorfrontend/FrontendAppConfig.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryWeeksController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryWeeksController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerStatutoryWeeksForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourStatutoryWeeksForm.scala
conf/application.conf
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryWeeksControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryWeeksControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerStatutoryWeeksFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourStatutoryWeeksFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerStatutoryWeeksViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourStatutoryWeeksViewSpec.scala

Maximum number of weeks is now dependant on the type of statutory pay

CCALC-3714 - Update validation of statutory pay weeks

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/approvedProvider.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/employmentIncomeCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursInfo.scala.html

Made link open in a new window for approved provider

approved provider link to open in new window

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/maxFreeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
conf/messages.en

Reverts hmrc/childcare-calculator-frontend#176

Revert "removed the read more information link as per donna instruction"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_date.scala.html
conf/messages.en

@versatil56 please review and merge

couple of accessibility issues fixed

---

app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MinimumHoursNavigator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MinimumHoursNavigatorSpec.scala

CCALC-3834 Fix navigation at the eligibility check points on the pages

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourChildController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/AboutYourChildForm.scala
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/AboutYourChildFormSpec.scala

@versatil56 I've branched off master and added validation for duplicate child names. Been over validation content with Stu and think the content is OK. Tested manually but will need to go to QA if we're happy.

CCALC-3818: Add validation for duplicate names

---

app/assets/stylesheets/childcarecalculatorfrontend-app.scss
app/assets/stylesheets/partials/_forms.scss
app/uk/gov/hmrc/childcarecalculatorfrontend/views/aboutYourResults.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala

Ccalc 3847

---

app/assets/stylesheets/childcarecalculatorfrontend-app.scss
app/assets/stylesheets/partials/_base.scss
app/assets/stylesheets/partials/_forms.scss
app/uk/gov/hmrc/childcarecalculatorfrontend/views/aboutYourChild.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/approvedProvider.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothIncomeInfoPY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/button_link.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/error_summary.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_check_box.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_number.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_radio.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_yes_no.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/submit_button.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/expectedChildcareCosts.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/maxFreeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerIncomeInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
conf/application.conf
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultNotEligibleViewSpec.scala

@tyagikumarvineet @versatil56  please review and merge

Ccalc 3871

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothAnyTheseBenefitsCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothAnyTheseBenefitsPY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/youAnyTheseBenefitsCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/youAnyTheseBenefitsPY.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothAnyTheseBenefitsCYViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothAnyTheseBenefitsPYViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YouAnyTheseBenefitsCYViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YouAnyTheseBenefitsPYViewSpec.scala

Done this as part of the ticket given to the prototype work - thought it would save some time. All tests ran and passed.

wrong list of benefits been shown to the user in income sections

---

conf/messages.en

CCALC-3907 - Messages updated for ESC vouchers 

---

conf/messages.en

changed welsh hours to be 380 not 390

---

app/assets/stylesheets/childcarecalculatorfrontend-app.scss

Feedback styles

---

app/uk/gov/hmrc/childcarecalculatorfrontend/guice/SplunkSubmissionModule.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/services/SplunkSubmissionService.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/services/SplunkSubmissionServiceSpec.scala

Added splunk connector. We can test this properly when we have the new feedback page.

CCALC-3958: Add splunk connector

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala

@versatil56 please review and merge

result page updated

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/SurveyChildcareSupportController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/SurveyDoNotUnderstandController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/guice/SplunkSubmissionModule.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/services/SplunkSubmissionService.scala
conf/application.conf
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/SurveyChildcareSupportControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/SurveyDoNotUnderstandControllerSpec.scala

Added auditing to first question of the exit survey (radio button).

CCALC-3962: Add Splunk auditing to SurveyChildcareSupport

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourResultsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoService.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/aboutYourResults.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourResultsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoService.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/AboutYourResultsViewSpec.scala

Updates to display relevant links on AboutYourResults page. Anuja has manually QA'd

CCALC-3934

---

app/assets/javascripts/polyfill.js

javascript added

---

app/assets/javascripts/polyfill.js

Ccalc 3914

---

conf/application-json-logger.xml

Reverts hmrc/childcare-calculator-frontend#265

Revert "CCALC-Add-Logger  Add log level WARN"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/SurveyDoNotUnderstandController.scala

Reverts hmrc/childcare-calculator-frontend#262

Revert "Feedback logging"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/actions/DataRetrievalAction.scala

Reverts hmrc/childcare-calculator-frontend#271

Revert "adding session id"

---

app/assets/stylesheets/childcarecalculatorfrontend-app.scss
app/uk/gov/hmrc/childcarecalculatorfrontend/views/aboutYourResults.scala.html

This is updating the look and feel ONLY of the feedback link on the more information about your results page. Tests ran.

updated the feedback link styling

---

app/uk/gov/hmrc/childcarecalculatorfrontend/FrontendAppConfig.scala
project/FrontendBuild.scala
project/plugins.sbt

Reverts hmrc/childcare-calculator-frontend#291

Revert "Ccalc 3815"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/FrontendAppConfig.scala
project/FrontendBuild.scala
project/plugins.sbt

Reverts hmrc/childcare-calculator-frontend#292

Ccalc 3815

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_date.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/input_number.scala.html

@versatil56 can you please merge

CCALC-4094 - input type updated to resolve issue raised by DAC

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala

@tyagikumarvineet @versatil56 please merge

CCALC-4095 change in circumstances content and test updated

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhatToTellTheCalculatorViewSpec.scala

Did this as part of my ticket for the prototype to save the DEV's some time. Added the line to the test files too, all passed.

added in new line for time to complete

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala

Have added the content in that was still missing from the live version and included the work for the ticket CCALC-4082. Dont think this needs any logic around as it should be relevant for every result and you wouldnt get here without getting something as GREEN.
I havent added the code to the tests so if this needs to be added in then someone will need to check this branch out first.

added in the content for your estimates and the changes in your income

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhatToTellTheCalculatorViewSpec.scala

@versatil56 @tyagikumarvineet please merge

content and test updated

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/doYouLiveWithPartner.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/DoYouLiveWithPartnerViewSpec.scala

@versatil56 @tyagikumarvineet please merge

content and test updates

---

app/uk/gov/hmrc/childcarecalculatorfrontend/utils/TCSchemeInEligibilityMsgBuilder.scala
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/utils/TCSchemeInEligibilityMsgBuilderSpec.scala

@tyagikumarvineet @versatil56 can you please merge

Ccalc 4093

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/scheme_result.scala.html

markup update

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala

Updated content on the 2 year old  and added the new content and lines to test file. This still needs to be added to the other results page.  This is in addition to CCALC-4092 which was just pulled in to master yesterday.

Ccalc 4106

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerChildcareVouchersController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourChildcareVouchersController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerChildcareVouchersForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourChildcareVouchersForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHousehold.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcare.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswers.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerChildcareVouchers.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourChildcareVouchers.scala.html
conf/messages.en
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerChildcareVouchersControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourChildcareVouchersControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerChildcareVouchersFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourChildcareVouchersFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHouseholdSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcareSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerChildcareVouchersViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourChildcareVouchersViewSpec.scala

Reverts hmrc/childcare-calculator-frontend#309

Revert "CCALC - 4087  Remove Not Sure option and Question for vouchers needs to be changed "

---

project/FrontendBuild.scala

@versatil56 I have upgraded bootstrap. lets see if it works

bootstrap upgraded

---

app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcare.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcareSpec.scala

CCALC-4125 - corrected eligibility to allow user to continue on journey if eligible for vouchers when have or could in future childcare costs

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothGetSameIncomePreviousYear.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/youGetSameIncomePreviousYear.scala.html

Both income a11y fix

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothGetSameIncomePreviousYear.scala.html

Reverts hmrc/childcare-calculator-frontend#358

Revert "table update"

---

app/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswers.scala
project/FrontendBuild.scala
project/MicroService.scala
project/plugins.sbt
test/uk/gov/hmrc/childcarecalculatorfrontend/DataHelpers.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/ChildcareNavigatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswersSpec.scala

DL-1247 config and fix tests in readiness for new build migration
**New Build** (delete as appropriate)
Updating config for new build and fix failing tests identified

DL-1247 applying config and fixing tests for new build migration

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AreYouInPaidWorkController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerChildcareVouchersController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/WhatToTellTheCalculatorController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourChildcareVouchersController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoGetsVouchersForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourChildcareVouchersForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHousehold.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcare.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoService.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswers.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/scheme_result.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerChildcareVouchers.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultEligible.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourChildcareVouchers.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerChildcareVouchersControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourChildcareVouchersControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHouseholdSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcareSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/ChildcareNavigatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/services/MoreInfoServiceSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerChildcareVouchersViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/SchemeResultViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourChildcareVouchersViewSpec.scala

DL-1267 October 2018 changes
**Fix** 
Updating pages and tests in accordance with DL-1267 for implementation to Live ready for October

DL-1267 changes applied for October changes

---

app/uk/gov/hmrc/childcarecalculatorfrontend/repositories/SessionRepository.scala

DL-1271
Date format for last updated

Date format for last update

---

conf/messages

~ DL1267voucherfix
**Bug fix** (delete as appropriate)
Removing reference to childcare voucher in Other Childcare Scheme section on result page.

DL-1267voucherfix text removal fr other childcare schemes

---

app/uk/gov/hmrc/childcarecalculatorfrontend/FrontendAppConfig.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/config/MicroserviceGlobal.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerStatutoryStartDateForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourStatutoryStartDateForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/jobs/ClearDataJob.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/jobs/JobConfig.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/repositories/SessionRepository.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/DateTimeUtils.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/TaxYearInfo.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/TaxYearResolver.scala
conf/application.conf
it/uk.gov.hmrc.childcarecalculatorfrontend/helpers/FakeConfig.scala
it/uk.gov.hmrc.childcarecalculatorfrontend/helpers/IntegrationSpecBase.scala
it/uk.gov.hmrc.childcarecalculatorfrontend/helpers/SessionHelper.scala
it/uk.gov.hmrc.childcarecalculatorfrontend/helpers/WiremockHelper.scala
project/FrontendBuild.scala
project/MicroService.scala
scalastyle-config.xml
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerStatutoryStartDateFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourStatutoryStartDateFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHouseholdSpec.scala

**Bug fix**
Added a scheduler to remove sensitive data from Production in response to this weeks incident.

DL-1287 Added scheduler to clear documents in production

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AboutYourChildController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerStatutoryStartDateForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourStatutoryStartDateForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/TaxYearInfo.scala
project/FrontendBuild.scala
project/MicroService.scala
project/plugins.sbt
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerStatutoryStartDateFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourStatutoryStartDateFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHouseholdSpec.scala

**Dependency uplift**
* Uplifted dependencies for `childcare-calculator-frontend`

DL-CCFE-dep-uplift Uplifted dependencies

---

project/FrontendBuild.scala

**Bug fix**
* Potential bug fix for deployments of CCFE

DL-CCFE-dep-uplift-fix Uplifted dependencies for CI fix

---

conf/nmw.conf
test/uk/gov/hmrc/childcarecalculatorfrontend/utils/UtilsSpec.scala

- [x ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [ x]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [ x]  I've executed the acceptance test pack locally to ensure there are no functional regressions
- [ x]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message

DL-1559: update nmw values in conf file

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultEligible.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html
conf/messages
project/FrontendBuild.scala
project/plugins.sbt
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerStatutoryStartDateControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/YourStatutoryStartDateControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/PartnerStatutoryStartDateFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourStatutoryStartDateFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHouseholdSpec.scala

**Bug fix** 
Content updates on results pages that were recommended in the live incident review. Also had to fix unit tests that were failing due to the new tax year.

DL 1779: Content changes to result pages

---

conf/application.conf

DL-1812 - Update feedback url
**Maintenance Fix** 
Update feedback url in accordance with platform changes.

DL-1812 updated Feedback url

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModel.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/ChildcareNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html
conf/app.routes
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ResultControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModelSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/ChildcareNavigatorSpec.scala

**Bug fix**
* Fixes to several missing or wrong content scenarios on childcare frontend when on the diverged non tax-credits route.

DL-1623-tweaks Resolved issues with tax credits on diverged route

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/maxFreeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultEligible.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/views/MaxFreeHoursInfoViewSpec.scala

**Bug fix** 
Fixing content issues outlined in v2 documentation for DL-1623.

DL-1623-v2changes updated tweaks to content following initial review

---

conf/nmw.conf

DL-2643 - update nmw settings for 2020

---

project/AppDependencies.scala

**New feature**
Updating  **simple-reactivemongo** dependency

DL-3737 updated ReactiveMongo

---

conf/application.conf
project/AppDependencies.scala

Added a11y statement link to the footer/updated play-ui to 8.12. a11y statement PR: https://github.com/hmrc/accessibility-statement-frontend/pull/131

DL-4230 - A11y statement functionality for Childcare calculator

---

app/uk/gov/hmrc/childcarecalculatorfrontend/filters/SessionIdFilter.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/repositories/SessionRepository.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/Utils.scala
build.sbt
project/AppDependencies.scala

DL-4483 Dependency update

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourAgeForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourPartnersAgeForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Enums.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHousehold.scala
conf/messages
conf/nmw.conf
test/uk/gov/hmrc/childcarecalculatorfrontend/cascadeUpserts/MaximumHoursCascadeUpsertSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/mappings/UserAnswerToHouseholdSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/utils/UtilsSpec.scala

Branch contains tax year changes including age band changes and changes to national minimum wages. Master branch has been reverted to before tax year changes and these changes must be merged and deployed on April 6th 2021.

ccc tax year changes

---

conf/nmw.conf

DL-5347 - updated nmw date

---

conf/application.conf

DL-5376 Updating assets version

---

app/uk/gov/hmrc/childcarecalculatorfrontend/FrontendAppConfig.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/actions/DataRetrievalAction.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/filters/Filters.scala
conf/application.conf
project/AppDependencies.scala

DL-5174 - upgraded bootstrap to 4.2.0 for auth-client update

---

conf/application.conf

DL-5432 - enabled cspFilters

---

conf/application.conf

DL-5432 - csp script-src used

---

app/assets/stylesheets/childcarecalculatorfrontend-app.scss
app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/scheme_result.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/govuk_wrapper.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/maxFreeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultEligible.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultNotEligibleViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/SchemeResultViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhatToTellTheCalculatorViewSpec.scala

DL-4767 - CCC Content Review and Change

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt

DL-5466 Auth-client upgrade

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/components/scheme_result.scala.html

DL-6073 - Moved Free Hours Contact Council section

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/govuk_wrapper.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/location.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/back_link.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/error_summary.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/heading.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_radio.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/submit_button.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/LocationViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ViewSpecBase.scala

DL-6212
- Updated location view
- Updated playComponents.back_link, playComponents.heading, playComponents.error_summary, playComponents.submit_button

DL-6212 Location view

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/childcareCosts.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ChildcareCostsViewSpec.scala

DL-6215 childcareCosts.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/Layout.scala.html

DL-6349 Moving HmrcLayout to GovukLayout

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursInfo.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/FreeHoursInfoViewSpec.scala

DL-6217
Note: heading component is fixed in DL-6213

DL-6217 Free hours info view

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/approvedProvider.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ApprovedProviderViewSpec.scala

DL-6216 approvedProvider.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/childAgedThreeOrFour.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ChildAgedThreeOrFourViewSpec.scala

DL-6214 - childAgedThreeOrFour.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourChildcareVouchers.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourChildcareVouchersViewSpec.scala

DL-6221 yourChildcareVouchers.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/doYouLiveWithPartner.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/views/DoYouLiveWithPartnerViewSpec.scala

DL-6218 - doYouLiveWithPartner.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/ApprovedProviderForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/ChildcareCostsForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/LocationForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoGetsBenefitsForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/approvedProvider.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/childAgedTwo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/childcareCosts.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/location.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whoGetsBenefits.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhoGetsBenefitsViewSpec.scala

DL-6223 Who gets benefits view

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoIsInPaidEmploymentForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whoIsInPaidEmployment.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhoIsInPaidEmploymentViewSpec.scala

DL-6219 - whoIsInPaidEmployment.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/childAgedTwo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/doYouOrYourPartnerGetAnyBenefits.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/DoYouOrYourPartnerGetAnyBenefitsViewSpec.scala

DL-6222 doYouOrYourPartnerGetAnyBenefits.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhichBenefitsYouGetForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Enums.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/detail_summary.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_check_box.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whichBenefitsYouGet.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhichBenefitsYouGetViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewCheckboxViewBehaviours.scala

DL-6224 whichBenefitsYouGet.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourAgeForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourAge.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourAgeViewSpec.scala

DL-6225 yourAge.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/TaxOrUniversalCreditsForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/taxOrUniversalCredits.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/TaxOrUniversalCreditsViewSpec.scala

DL-6228 taxOrUniversalCredits.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/freeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourMinimumEarnings.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourMinimumEarningsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewViewBehaviours.scala

DL-6226 Your minimum earnings view

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefitsIncomeCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_text.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BenefitsIncomeCYViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewQuestionViewBehaviours.scala

DL-6257
- New UI component added for **input_text**

DL-6257 Benefits income current year page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/childDisabilityBenefits.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ChildDisabilityBenefitsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewViewBehaviours.scala

DL-6231 childDisabilityBenefits.scala.html

---

test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewViewBehaviours.scala

DL-5851 Fix test

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/expectedChildcareCosts.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/noOfChildren.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_number.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ChildDisabilityBenefitsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ExpectedChildcareCostsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourMinimumEarningsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewBigDecimalViewBehaviours.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewViewBehaviours.scala

DL-6235 expectedChildcareCosts.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhichDisabilityBenefitsForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/Enums.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whichDisabilityBenefits.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhichDisabilityBenefitsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewViewBehaviours.scala

DL-6232 - whichDisabilityBenefits.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/childRegisteredBlind.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ChildRegisteredBlindViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewViewBehaviours.scala

DL-6233 childRegisteredBlind.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerChildcareVouchers.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerChildcareVouchersViewSpec.scala

DL-6242 partnerChildcareVouchers.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentWorkHoursController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/parentWorkHours.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentWorkHoursControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ParentWorkHoursViewSpec.scala

- Amended spacing on `whatToTellTheCalculator`

DL-6220 - parentWorkHours.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothPaidWorkCY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothPaidWorkCYViewSpec.scala

DL-6238 - bothPaidWorkCY

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerPaidWorkCY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerPaidWorkCYViewSpec.scala

DL-6237 partnerPaidWorkCY.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerWorkHoursController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerWorkHours.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerWorkHoursControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerWorkHoursViewSpec.scala

DL-6241 partnerWorkHours.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/aboutYourChild.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_date.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/AboutYourChildViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/behaviours/NewDateViewBehaviours.scala

DL-6230 Latest code

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/YourPartnersAgeForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourPartnersAge.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourPartnersAgeViewSpec.scala

DL-6243 yourPartnersAge.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerMaximumEarnings.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerMaximumEarningsViewSpec.scala

DL-6245 partnerMaximumEarnings.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothPaidPensionCY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothPaidPensionCYViewSpec.scala

DL-6248 bothPaidPensionCY.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/parentPaidWorkCY.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ParentPaidWorkCYViewSpec.scala

DL-6246 parentPaidWorkCY.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/employmentIncomeCY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/EmploymentIncomeCYViewSpec.scala

DL-6247 employmentIncomeCY.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/SessionExpiredController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/Layout.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whatToTellTheCalculator.scala.html

DL-6239 Timeout dialog added to layout

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchYouPayPension.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/HowMuchYouPayPensionViewSpec.scala

DL-6250 howMuchYouPayPension.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoPaysIntoPensionForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whoPaysIntoPension.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhoPaysIntoPensionViewSpec.scala

DL-6249 whoPaysIntoPension.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/ChildcarePayFrequencyForm.scala

DL-6234 Childcare pay frequency capitalizations

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoPaysIntoPensionForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhosHadBenefitsForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whosHadBenefits.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhosHadBenefitsViewSpec.scala

DL-6254 whosHadBenefits.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchPartnerPayPension.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/HowMuchPartnerPayPensionViewSpec.scala

DL-6251 howMuchPartnerPayPension.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchBothPayPension.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/HowMuchBothPayPensionViewSpec.scala

DL-6252 howMuchBothPayPensionView

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/youPaidPensionCY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YouPaidPensionCYViewSpec.scala

DL-6281 youPaidPensionCy page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/eitherOfYouMaximumEarnings.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/EitherOfYouMaximumEarningsViewSpec.scala

DL-6275 eitherOfYouMaximumEarnings page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerPaidPensionCY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerPaidPensionCYViewSpec.scala

DL-6282 partnerPaidPensionCY.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerPaidWorkPY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerPaidWorkPYViewSpec.scala

DL-6291 partnerPaidWorkPY.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothOtherIncomeLY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothOtherIncomeLYViewSpec.scala

DL-6296 bothOtherIncomeLY.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothPaidWorkPY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothPaidWorkPYViewSpec.scala

DL-6292 bothPaidWorkPY.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/childAgedThreeOrFour.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerBenefitsIncomePY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerBenefitsIncomePYViewSpec.scala

DL-6304 - partnerBenefitsIncomePY

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchBothPayPensionPY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/HowMuchBothPayPensionPYViewSpec.scala

DL-6307 howMuchBothPayPensionPY.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerStatutoryWeeks.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerStatutoryWeeksViewSpec.scala

DL-6328 partnerStatutoryWeeks.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerStatutoryStartDate.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerStatutoryStartDateViewSpec.scala

DL-6330 partnerStatutoryStartDate.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourStatutoryPayBeforeTax.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourStatutoryPayBeforeTaxViewSpec.scala

DL-6331 yourStatutoryPayBeforeTax.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourStatutoryStartDate.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourStatutoryStartDateViewSpec.scala

DL-6329 yourStatutoryStartDate.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourStatutoryPayPerWeek.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourStatutoryPayPerWeekViewSpec.scala

DL-6333 yourStatutoryPayPerWeek.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerStatutoryPayBeforeTax.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerStatutoryPayBeforeTaxViewSpec.scala

DL-6332 partnerStatutoryPayBeforeTax.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerStatutoryPayPerWeek.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerStatutoryPayPerWeekViewSpec.scala

DL-6334 partnerStatutoryPayPerWeek.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothIncomeInfoPY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothIncomeInfoPYViewSpec.scala

DL-6342 bothIncomeInfoPY.scala.html

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/bothGetSameIncomePreviousYear.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerIncomeInfo.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/BothGetSameIncomePreviousYearViewSpec.scala

DL-6338 bothGetSameIncomePreviousYear.scala

---

app/uk/gov/hmrc/childcarecalculatorfrontend/handlers/ErrorHandler.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/error_template.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/components/ErrorSummaryViewSpec.scala

DL-6339 - error_template

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoWasInPaidWorkPYForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/whoWasInPaidWorkPY.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/WhoWasInPaidWorkPYViewSpec.scala

DL-6715 whoWasInPaidWorkPY

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/childrenDisabilityBenefits.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ChildrenDisabilityBenefitsViewSpec.scala

DL-6716 - childrenDisabilityBenefits

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/expectedChildcareCosts.scala.html

DL-6755 expectedChildcareCosts.scala hint text

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/noOfChildren.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/parentWorkHours.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerStatutoryWeeks.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerWorkHours.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_number.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_text.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourStatutoryWeeks.scala.html

DL-6751 - shortened input box for short answers

---

app/uk/gov/hmrc/childcarecalculatorfrontend/Navigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/ParentWorkHoursController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/PartnerWorkHoursController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhichBenefitsPartnerGetForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhichBenefitsYouGetForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/handlers/ErrorHandler.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/Layout.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/childcarePayFrequency.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/detail_summary.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_number.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_text.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_textarea.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/list.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/tableList.scala.html
build.sbt
project/plugins.sbt

DL-6785 clean up and dependency update

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/scheme_result.scala.html

DL-5437 - Removed duplicate Ids

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/employmentIncomePY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/expectedChildcareCosts.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchPartnerPayPension.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchPartnerPayPensionPY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchYouPayPension.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/howMuchYouPayPensionPY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/noOfChildren.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerBenefitsIncomeCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerBenefitsIncomePY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerOtherIncomeAmountCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerOtherIncomeAmountPY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerStatutoryPayPerWeek.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerStatutoryWeeks.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/input_number.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/list.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/youBenefitsIncomeCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/youBenefitsIncomePY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourOtherIncomeAmountCY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourOtherIncomeAmountPY.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourStatutoryPayPerWeek.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourStatutoryWeeks.scala.html

Fixed issues in the Jenkins a11y report: https://build.tax.service.gov.uk/job/DDCT%20Live%20Services/job/Childcare%20Calculator/job/cc-calculator-accessibility-tests/6/Accessibility_20Check_20Report/
- Removed ids from bullet list items
- Moved `h1` headings out of labels

DL-5437 - VNU violation amendments

---

conf/messages.cy

DL-7785 added welsh for error

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html

**New feature**
Some text in the further information section of the results page needed to be different depending on if the user selects yes or no living with a partner towards the start of the journey.

DL-7820 - dynamic results content

---

app/uk/gov/hmrc/childcarecalculatorfrontend/repositories/SessionRepository.scala
conf/application.conf
project/AppDependencies.scala

DL-9019 - Changed repository to use hmrc-mongo

---

build.sbt
conf/application.conf
project/AppDependencies.scala

DL-9990 remove targetJvm

---

README.md

DL-9884 update READ.me file

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/whichChildrenBlind.scala.html
conf/messages
conf/messages.cy

DL-10687 add hint text for whichChildernBlind page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/maxFreeHoursInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/scheme_result.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html

DL-11413 Accessibility fixes for pages with multiple H1's

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/eitherOfYouMaximumEarnings.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerMaximumEarnings.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/playComponents/link.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourMaximumEarnings.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/EitherOfYouMaximumEarningsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerMaximumEarningsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourMaximumEarningsViewSpec.scala

DL-11176 fixed content and formatting

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/Layout.scala.html

DL-11949 Convert layout to use hmrcStandardPage

---

conf/application.conf
conf/messages
conf/messages.cy
project/plugins.sbt

DL-12074 updated internal error message

---

project/AppDependencies.scala

DL-12317 update play-frontend-hmrc version

---

build.sbt
conf/application.conf
conf/prod.routes

DL-12418 fixed issues

---

app/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsService.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/resultNotEligible.scala.html
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultNotEligibleViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/ResultViewSpec.scala

DL-12737 fixed result page issue

---

conf/nmw.conf

DL-12791 - nmw changed for 2024

---

conf/nmw.conf

fixing min wage bracket

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetCarersAllowanceController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetCarersAllowanceController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doYouGetCarersAllowance.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doesPartnerGetCarersAllowance.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetCarersAllowanceControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetCarersAllowanceControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala

DL-13647 A/B Test Prep - Carer's allowance page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetSevereDisabilityPremiumController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetSevereDisabilityPremiumController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doYouGetSevereDisabilityPremium.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doesPartnerGetSevereDisabilityPremium.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetSevereDisabilityPremiumControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetSevereDisabilityPremiumControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/DoYouGetSevereDisabilityPremiumViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/DoesPartnerGetSevereDisabilityPremiumViewSpec.scala

DL-13649 Severe Disability Premium page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetIncomeBasedBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetIncomeBasedBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doYouGetIncomeBasedBenefits.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doesPartnerGetIncomeBasedBenefits.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetIncomeBasedBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetIncomeBasedBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala

DL-13648 A/B Test Prep - Income Based Benefits page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetHigherRateDisabilityBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetHigherRateDisabilityBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doYouGetHigherRateDisabilityBenefits.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doesPartnerGetHigherRateDisabilityBenefits.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoYouGetHigherRateDisabilityBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/DoesPartnerGetHigherRateDisabilityBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala

DL-13651 A/B Test Prep - Higher rate disability benefits page

---

app/uk/gov/hmrc/childcarecalculatorfrontend/cascadeUpserts/MaximumHoursCascadeUpsert.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/WhoGetsTheBenefitsController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoGetsTheBenefitsForm.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/identifiers/benefits/WhoGetsTheBenefitsId.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/ChildcareConstants.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/utils/UserAnswers.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/doYouOrPartnerGetBenefits.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/whoGetsTheBenefits.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/benefits/WhoGetsTheBenefitsControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/WhoGetsTheBenefitsFormSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/DoYouOrPartnerGetBenefitsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/benefits/WhoGetsTheBenefitsViewSpec.scala

DL-13855 Split first partner benefits page in two

---

app/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsService.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsServiceSpec.scala

DL-12793 restoring england only guard for error msg

---

app/uk/gov/hmrc/childcarecalculatorfrontend/repositories/SessionRepository.scala

Added implicit `Format` for Instant to `DatadCacheMap`, and changed upsert to replace documents so that `lastUpdated` remains as a date type and is not converted to JsString. Also added a task to change all existing documents with their `lastUpdated` field as a string to date (to be removed once the changes have deployed).

DL-13672 - Changed TTL to date format

---

app/uk/gov/hmrc/childcarecalculatorfrontend/repositories/SessionRepository.scala

DL-13672 - Removed TTL correction logic

---

app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MinimumHoursNavigator.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MinimumHoursNavigatorSpec.scala

DL-13812 correction to free hours flow

---

app/uk/gov/hmrc/childcarecalculatorfrontend/models/SchemeResults.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/services/EligibilityServiceSpec.scala

DL-14174 removed unused parameters passed from cc-eligibility

---

project/AppDependencies.scala
project/plugins.sbt

DL-15603:Updating the service with latest version of dependencies.

---

conf/nmw.conf

Childcare allowance rates updated for age and job groups

DL-15043-Rates Updated for 2025 and 2026

---

project/AppDependencies.scala
project/plugins.sbt

DL-15288: upgraded bootstrapFrontendVersion

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerIncomeInfo.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourIncomeInfo.scala.html
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerIncomeInfoViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourIncomeInfoViewSpec.scala

DL-15416: Content change in Income info
New feature

DL-15416: Content change in Income info

---

app/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AverageWeeklyEarningController.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerAverageWeeklyEarnings.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourAndPartnerAverageWeeklyEarnings.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourAverageWeeklyEarnings.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/controllers/AverageWeeklyEarningControllerSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/navigation/MaximumHoursNavigatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerAverageWeeklyEarningsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourAndPartnerAverageWeeklyEarningsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourAverageWeeklyEarningsViewSpec.scala

DL-15410: Added average Weekly earnings page and changed the navigation
New feature

DL-15410: Added average Weekly earnings page and changed the navigation

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerMinimumEarnings.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourMinimumEarnings.scala.html
conf/messages
conf/messages.cy
test/uk/gov/hmrc/childcarecalculatorfrontend/views/PartnerMinimumEarningsViewSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/views/YourMinimumEarningsViewSpec.scala

DL-15411:Change content of will you earning page

DL-15411:Change content of will you earning page 

---

conf/nmw.conf

DL-15043 updating NMW effective start date

---

app/uk/gov/hmrc/childcarecalculatorfrontend/forms/AboutYourChildForm.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/forms/AboutYourChildFormSpec.scala

DL-15413-V2: Modified references to age 20 to age 18 in spec files

---

app/uk/gov/hmrc/childcarecalculatorfrontend/models/SchemeResults.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/EmploymentSupportedChildcare.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/FreeChildcareEligibilityCalculator.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/FreeChildcareWorkingParents.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/TaxFreeChildcare.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/tfc/ModelFactory.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/tfc/Models.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModel.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/services/EligibilityService.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsService.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/SchemeResultsSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/FreeChildcareEligibilityCalculatorSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/FreeChildcareWorkingParentsSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/TaxFreeChildcareSpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/models/schemes/tfc/ModelFactorySpec.scala
test/uk/gov/hmrc/childcarecalculatorfrontend/services/ResultsServiceSpec.scala

After introducing different set of parents benefits, the rules for schemes eligibility changed too.

DL-15475 Implement backend logic for new benefits

---

app/uk/gov/hmrc/childcarecalculatorfrontend/models/Enums.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/SchemeResults.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModel.scala
app/uk/gov/hmrc/childcarecalculatorfrontend/views/result.scala.html
conf/messages
test/uk/gov/hmrc/childcarecalculatorfrontend/models/views/ResultsViewModelSpec.scala

DL-15668: Removed remaining backend depenedent TC code

---

app/uk/gov/hmrc/childcarecalculatorfrontend/views/partnerAverageWeeklyEarnings.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourAndPartnerAverageWeeklyEarnings.scala.html
app/uk/gov/hmrc/childcarecalculatorfrontend/views/yourAverageWeeklyEarnings.scala.html
conf/messages
conf/messages.cy

DL-15728 : Fixed issues found in demo

---

conf/messages
conf/messages.cy

DL-15728: Updated msg

---

conf/messages
conf/messages.cy

DL-16055: added missing neonatal

---

project/AppDependencies.scala

DL-16660: Updated frontend play version

---

.gitignore
build.sbt
precheck.sh
project/AppDependencies.scala
project/plugins.sbt

**Bug fix** (delete as appropriate)
Update dependencies to fix a bobby violation on bootstrap version `9.13.0`.

DL-16916: Update dependencies to fix bobby violation
